name: Backend CI Pipeline

# 워크플로우 실행 트리거 설정
on:
  push:
    branches:
      - dev        # dev 브랜치에 푸시되면 실행
      - main       # main 브랜치에 푸시되면 실행
  pull_request:
    branches:
      - dev        # dev 브랜치 대상 PR 생성/업데이트 시 실행
  workflow_dispatch:  # 수동 실행 버튼 활성화

jobs:
  build-and-push:
    # 워크플로우가 실행될 환경
    runs-on: ubuntu-latest

    # 권한 설정 (GHCR 패키지 쓰기 위해)
    permissions:
      contents: read      # 코드 리포지터리 읽기 권한
      packages: write     # GHCR에 이미지 push 권한

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        # 리포지터리 소스를 워크플로우 환경에 체크아웃

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'        # JDK 17 설치
          distribution: 'temurin'   # Temurin 배포판 사용

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
        # 현재 디렉터리의 Dockerfile을 이용해 최신 이미지 빌드, 태그는 ghcr.io 리포지터리 경로 + latest

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}        # 자동으로 실행하는 GitHub 사용자명
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions 기본 제공 토큰으로 로그인

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
        # 빌드한 이미지를 GHCR에 업로드(push)
